name: 'Add assets to release'
permissions:
  contents: 'write'
'on':
  release:
    types: ['published']
concurrency:
  group: 'release'
defaults:
  run:
    shell: 'bash'
jobs:
  publish_asstes:
    name: 'Publish Assets'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # v5.0.0
      - uses: 'extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff' # v3
      - name: 'Publish Assets'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          just build-all "${GITHUB_REF#refs/tags/}"
          just publish-assets "${GITHUB_REF#refs/tags/}"
