---

name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run Renovate
        uses: renovatebot/github-action@ea850436a5fe75c0925d583c7a02c60a5865461d # v43.0.20
        with:
          configurationFile: "renovate-config.json"
          token: ${{ secrets.RENOVATE_TOKEN }}
