---

name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run Renovate
        uses: renovatebot/github-action@9ba84f1ade243f8c2ce5b223df61cf23dc094584 # v43.0.13
        with:
          configurationFile: "renovate-config.json"
          token: ${{ secrets.RENOVATE_TOKEN }}
