---

name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run Renovate
        uses: renovatebot/github-action@a3c115cd6676c8a5bc72f9715f108759e570daf5 # v43.0.19
        with:
          configurationFile: "renovate-config.json"
          token: ${{ secrets.RENOVATE_TOKEN }}
